### ISSUE TITLE
Consider alternative hosting of binaries.

### ISSUE THREAD

**Issue by kiljacken** [jmi2k/zig-playground#1]
Hey!

Nice job on this, but if you plan to update the binaries at some point you really shouldn't be using git for storing them. Git isn't exactly good at storing binary files, so a lot of space get's wasted as the repository has to store each version of the binaries.

**Comment by omixann** [comment]
Yes, I thought of 'binary distribution' as a temporary solution, while Zig is in a very early development stage and binaries aren't provided officially. But you are right, git isn't the right solution. Where do you recommend storing them? I can add a rule to Makefile to download them from another location.

**Comment by kiljacken** [comment]
I'm not really sure about alternative storage.

One way to go about it is to have a bogo github release, as these allow hosting of binaries outside the git repository itself. Then you could download them from there via the makefile.

**Comment by omixann** [comment]
I'm not sure of how GitHub releases work, but are you suggesting me to make periodic releases with the binaries attached as zip files? It seems fine.

**Comment by kiljacken** [comment]
Yeah something along those lines.

**Comment by omixann** [comment]
Ok. Next time I update binaries, I'll attach them to a release.

**Comment by kiljacken** [comment]
:+1:
